package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, REMOVE_NODE,
	ADD_FRIEND, ASK_VIEW, SEND_FILES, REMOVE, BACKUP,
	PING, PONG, CHECK_ASK, CHECK_TELL,
	TOKEN, LAMPORT_REPLY, LAMPORT_RELEASE, LAMPORT_REQUEST
}
